name: 'Code Review GitHub Action'
description: 'Automated code review for pull requests'
author: 'Jesse'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  providers:
    description: 'AI providers to use (comma-separated)'
    required: true
  chunk-size:
    description: 'Chunk size for processing diff'
    required: false
    default: '2000'
  review-focus:
    description: 'Review focus areas (comma-separated)'
    required: false
    default: 'security,performance,style'
  skip-patterns:
    description: 'File patterns to skip (comma-separated)'
    required: false
    default: ''
  openai-api-keys:
    description: 'OpenAI API keys (multiline)'
    required: false
  claude-api-keys:
    description: 'Claude API keys (multiline)'
    required: false
  gemini-api-keys:
    description: 'Gemini API keys (multiline)'
    required: false
outputs:
  review_summary:
    description: 'Summary of the code review'
  files_reviewed:
    description: 'Number of files reviewed'
  issues_found:
    description: 'Number of issues found'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'blue'