# Basic AI Code Review Workflow
# This is a minimal configuration for getting started with AI code review

name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    name: AI Code Review

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AI Code Review
        uses: your-username/code-review-action@latest
        with:
          # Required: GitHub token with pull-requests: write permissions
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # Required: At least one provider API keys array
          # Configure these as repository secrets in JSON array format
          openai-api-keys: ${{ secrets.OPENAI_API_KEYS }}
          claude-api-keys: ${{ secrets.CLAUDE_API_KEYS }}
          gemini-api-keys: ${{ secrets.GEMINI_API_KEYS }}

          # Optional: Specify which providers to use (default: all available)
          providers: 'openai,claude,gemini'

          # Optional: Focus areas for review (default: security,performance,style)
          review-focus: 'security,performance,style'

          # Optional: Max chunk size for processing large PRs (default: 2000)
          chunk-size: '2000'

          # Optional: File patterns to skip (default: *.min.js,package-lock.json)
          skip-patterns: '*.min.js,package-lock.json,dist/*,node_modules/*'

# Required Repository Secrets Setup:
#
# 1. Go to your repository Settings → Secrets and variables → Actions
# 2. Add these repository secrets:
#
#    OPENAI_API_KEYS:
#    ["sk-your-openai-key-1", "sk-your-openai-key-2"]
#
#    CLAUDE_API_KEYS:
#    ["sk-ant-your-claude-key-1", "sk-ant-your-claude-key-2"]
#
#    GEMINI_API_KEYS:
#    ["AIza-your-gemini-key-1", "AIza-your-gemini-key-2"]
#
# 3. The action will automatically round-robin through these keys
#    to distribute load and handle rate limits.